# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build-Go

on:
  push:
    branches-ignore:
      - "main"

permissions:
    contents: read

jobs:

  build:
    name: Build binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - {GOOS: linux, GOARCH: amd64}
          - {GOOS: linux, GOARCH: arm64}
          - {GOOS: darwin, GOARCH: amd64}
          - {GOOS: darwin, GOARCH: arm64}

    steps:
        - uses: actions/checkout@v4
    
        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.24'
    
        - name: Build
          run: |
            VERSION="$(git describe --tags)"
            DIR="$(mktemp -d)"
            mkdir "$DIR/age"        
            go build -v -o "$DIR/age" -ldflags "-X main.Version=$VERSION" -trimpath ./cmd/...
            tar -cvzf "age-$VERSION-$GOOS-$GOARCH.tar.gz" -C "$DIR" age
          env:
            CGO_ENABLED: 0
            GOOS: ${{ matrix.GOOS }}
            GOARCH: ${{ matrix.GOARCH }}

        - name: Upload workflow artifacts
          uses: actions/upload-artifact@v4
          with:
              name: age-binaries-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
              path: age-*
  upload:
      name: Upload release binaries
      runs-on: ubuntu-latest
      needs: build
      permissions:
          contents: write

      steps:
          - name: Download workflow artifacts
            uses: actions/download-artifact@v4
            with:
                pattern: age-binaries-*
                merge-multiple: true
          - name: Upload release artifacts
            run: gh release upload "$GITHUB_REF_NAME" age-*
            env:
                GH_REPO: ${{ github.repository }}
                GH_TOKEN: ${{ github.token }}      

